### ISSUE TITLE
Comment on site

### ISSUE THREAD

**Issue by AnastasiiaMamaeva** [b-joshua/b-joshua.github.io#1]
Hi! Very informative site and nice picture! You can make it next to the text introducing this HTML code: 
`<img  src="link_to_your_picture"  style="float:right; margin-right;"/>`

**Comment by b-joshua** [comment]
Nice tip! Thanks. I changed the photo location on the page to be beside the text.

**Comment by AnastasiiaMamaeva** [comment]
@liroh99
